### PR TITLE
Fix state modules failing with unexpected kwarg __pub_jid

### PR DESCRIPTION
**Pull request by andzn**
### What does this PR do?
Fixes a bug where applying states that contained state functions that did not support kwargs failed with the following erorr: "got an unexpected keyword argument '__pub_jid'"

### What issues does this PR fix or reference?
This was introduced by #13 and is needed by the software installation progress to work.

### Previous Behavior
__pub_jid was passed using kwargs which broke state functions that did not support kwargs

### New Behavior
__pub_jid is injected using global variables in state modules. state modules can then forward this to execution modules using kwargs

### Tests written?
No. 

### Commits signed with GPG?
No

### CODE REVIEW

File: salt/states/pkg.py [hunk 1]
```diff
@@ -2465,6 +2466,7 @@ def latest(
             desired_pkgs = [name]
 
     kwargs['saltenv'] = __env__
+    kwargs['__pub_jid'] = __jid__
```
Comment (rares-pop) [inline salt/states/pkg.py:2469]: Does this look ok?

**Review by romynior — APPROVED** [review]
